# Generated by Django 4.1.4 on 2023-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.PositiveSmallIntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('LOT', models.CharField(max_length=100)),
                ('VIN', models.CharField(max_length=17, unique=True)),
                ('site', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('sold', 'Sold'), ('yard', 'In Yard'), ('remove_engine', 'Engine Removed')], max_length=20)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
