# Generated by Django 4.1.7 on 2023-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='storage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('yard', 'In Yard'), ('remove_engine', 'Remove Engine')], max_length=20),
        ),
    ]
