# Generated by Django 4.1.7 on 2023-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_others_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='LOT',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
