# Generated by Django 4.1.7 on 2023-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='buyer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='site',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
