# Generated by Django 4.1.7 on 2023-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_dismantle_car_transport_car_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='buyer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
