# Generated by Django 4.1.7 on 2023-03-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_dismantle_alter_car_fixed_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ac_compressor', 'A/C COMPRESSOR'), ('abs_module', 'ABS MODULE'), ('airbag', 'AIRBAG'), ('alternator', 'ALTERNATOR'), ('battery', 'BATTERY'), ('body_control_module', 'BODY CONTROL MODULE'), ('booster', 'BOOSTER')], max_length=20)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('VIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.car')),
            ],
        ),
    ]
