# Generated by Django 4.1.7 on 2023-03-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('in_the_car', 'IN THE CAR'), ('in_stock', 'IN STOCK'), ('sold', 'SOLD')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
