# Generated by Django 4.1.7 on 2023-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_part_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(choices=[('ac_compressor', 'A/C COMPRESSOR'), ('abs_module', 'ABS MODULE'), ('airbag', 'AIRBAG'), ('alternator', 'ALTERNATOR'), ('battery', 'BATTERY'), ('body_control_module', 'BODY CONTROL MODULE'), ('booster', 'BOOSTER'), ('brake_caliper_front_left', 'BRAKE CALIPER FRONT LEFT'), ('brake_caliper_front_right', 'BRAKE CALIPER FRONT RIGHT')], max_length=50),
        ),
    ]
