# Generated by Django 4.1.7 on 2023-03-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_part_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(choices=[('ac_compressor', 'A/C COMPRESSOR'), ('abs_module', 'ABS MODULE'), ('airbag', 'AIRBAG'), ('alternator', 'ALTERNATOR'), ('battery', 'BATTERY'), ('body_control_module', 'BODY CONTROL MODULE'), ('booster', 'BOOSTER'), ('brake_caliper_front_left', 'BRAKE CALIPER FRONT LEFT'), ('brake_caliper_front_right', 'BRAKE CALIPER FRONT RIGHT'), ('brake_caliper_rear_left', 'BRAKE CALIPER REAR LEFT'), ('brake_caliper_rear_right', 'BRAKE CALIPER REAR RIGHT'), ('catalyst', 'CATALYST'), ('climate_control_module', 'CLIMATE CONTROL MODULE'), ('drive_axle_front_left', 'DRIVE AXLE FRONT LEFT'), ('drive_axle_front_right', 'DRIVE AXLE FRONT RIGHT'), ('drive_axle_rear_left', 'DRIVE AXLE REAR LEFT'), ('drive_axle_rear_right', 'DRIVE AXLE REAR RIGHT'), ('electronic_throttle_body', 'ELECTRONIC THROTTLE BODY'), ('engine', 'ENGINE'), ('engine_control_module', 'ENGINE CONTROL MODULE'), ('eps_column', 'EPS COLUMN'), ('eps_rack', 'EPS RACK'), ('fan_from_radiator', 'FAN FROM RADIATOR'), ('footweel_module', 'FOOTWEEL MODULE'), ('inverter_hybrid_voltage_converter', 'INVERTER / HYBRID VOLTAGE CONVERTER'), ('manual_racks', 'MANUAL RACKS'), ('passenger_inflator', 'PASSENGER INFLATOR'), ('power_booster', 'POWER BOOSTER'), ('power_steering_pump', 'POWER STEERING PUMP'), ('rack_pinion_power', 'RACK & PINION POWER'), ('radiator', 'RADIATOR'), ('radio_audio', 'RADIO / AUDIO'), ('salvage', 'SALVAGE'), ('starter', 'STARTER'), ('tipm', 'TIPM'), ('tires', 'TIRES'), ('transfer_case', 'TRANSFER CASE'), ('transmission', 'TRANSMISSION'), ('transmission_control_module', 'TRANSMISSION CONTROL MODULE'), ('wheels', 'WHEELS'), ('wire', 'WIRE')], max_length=50),
        ),
    ]
