# Generated by Django 4.1.7 on 2023-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_part_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
