# Generated by Django 4.1.7 on 2023-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('yard', 'In Yard'), ('remove_engine', 'Remove Engine'), ('dismantled', 'Dismantled')], max_length=20),
        ),
    ]
